

# --------------------------------
# BASE

server:
  port: 18082
  servlet.context-path: /v1.0


spring:
  profiles.active:
  - proj-default
  - proj-local
  #- proj-test
  #- proj-real
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.time-zone: UTC+9
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: true


logging:
  file:
    path: logs/link/
    max-size: 10MB
    max-history: 30         # delete after a month
  pattern:
    console: "%clr(%d{HH:mm:ss} %p){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info
    
    #org.tain.utils.TransferStrAndJson: trace


---
# --------------------------------------------------------
spring.profiles: proj-default

proj-env:
  base:
    name: lightnet project
    program: KieaLightnet-02-link-10.jar
    version: ver 1.0_2020.09.01
    comment: This is lightnet project.

  param:
    name: parameters
    access-token:  12345678901234567890abcde
    commit-file:   /KANG/json/virtual/commit_res2.json
    detail-file:   /KANG/json/virtual/detail_res.json
    list-file:     /KANG/json/virtual/list_res_v1.json
    list1-file:    /KANG/json/virtual/list_res_v1.1.json
    validate-file: /KANG/json/virtual/validate_res2.json

  job:
    name: job variables
    lightnet-url:
    - http://localhost:18888
    - https://192.10.2.141
    - https://192.10.2.38
    - https://test-public.lightnetapis.io
    - https://test-internal-system.lightnetapis.io
    - https://test1-internal-system.lightnetapis.io
    - https://test2-internal-system.lightnetapis.io
    lightnet-start-idx: 0
    auth-url: http://localhost:18081/v1.0/auth/auth
    callback-url: http://localhost:18084/v1.0/callback/callback
    
  json:
    name: default json   # not used
#---
# --------------------------------------------------------
#spring.profiles: proj-local
#
#proj-env:
#  job:
#    name: job variables
#    #lightnet-url:
#    #- https://test-public.lightnetapis.io
#    #lightnet-start-idx: 0
#    #auth-url: http://localhost:18081/v1.0/auth/auth
#    #callback-url: http://localhost:18084/v1.0/callback/callback
#    
#  json:
#    name: local json
#  url:
#    lightnet: http://localhost:18888
#    auth: http://localhost:18081/v1.0
#    link: http://localhost:18082/v1.0
#    mapper: http://localhost:18086/v1.0

---
# --------------------------------------------------------
# virtual test
spring.profiles: proj-local

proj-env:
  json:
    name: local json
  url:
    localhost: http://localhost:18888
    lightnet1: http://localhost:18888
    lightnet11: http://localhost:18888
    auth: http://localhost:18081/v1.0
    link: http://localhost:18082/v1.0
    mapper: http://localhost:18086/v1.0

---
# --------------------------------------------------------
# https://
spring.profiles: proj-test

proj-env:
  json:
    name: test json
  url:
    localhost: http://localhost:18888
    lightnet1: https://test-public.lightnetapis.io/v1
    lightnet11: https://test-public.lightnetapis.io/v1.1
    auth: http://localhost:18081/v1.0
    link: http://localhost:18082/v1.0
    mapper: http://localhost:18086/v1.0

---
# --------------------------------------------------------
spring.profiles: proj-dfep

proj-env:
  json:
    name: test json
  url:
    localhost: http://localhost:18888
    lightnet1: http://test-hawis.lightnetapis.io/v1
    lightnet11: http://test-hawis.lightnetapis.io/v1.1
    auth: http://localhost:18081/v1.0
    link: http://localhost:18082/v1.0
    mapper: http://localhost:18086/v1.0

---
# --------------------------------------------------------
spring.profiles: proj-real

proj-env:
  json:
    name: real json




