



spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    url: jdbc:h2:mem:infodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  
  devtools:
    livereload.enabled: true

  output:
    ansi:
      enabled: DETECT     # ALWAYS / NEVER / DETECT
      # FATAL and ERROR – Red
      # WARN – Yellow
      # INFO, DEBUG and TRACE – Green

########################################################
json:
  table-file:
    meta: src/main/resources/table/table_meta.json
    group: src/main/resources/table/table_group.json
    field-info: src/main/resources/table/table_field_info.json

    lightnet: src/main/resources/table/lightnet.json



########################################################
########################################################
spring.profiles.active: local-http #, logging-dev

---
spring:
  profiles: local-http
  
server.port: 8087


---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey
    

#########################################################
#
# $ java -jar application.jar --spring.profiles.active=logging-debug,logging-daily
#
---
spring:
  profiles: logging-dev

logging:
  # path: aaa
  file:
    filenamePattern: myfile. % d {yyyy-MM-dd-HH-mm-ss} .log
  # file: /logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    # level:
  level:
    root: debug
    org.tain.controller: debug
    org.tain.service: debug
    org.tain.repository: debug
    org.tain.domain: debug

---
spring:
  profiles: logging-prod

logging:
  file: /logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: error
    org.tain.controller: warn
    org.tain.service: info
    org.tain.repository: debug
    org.tain.domain: trace

---
spring.profiles: logging-info
logging:
  file: logs/application.log
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.quartz.core: INFO
    org.h2.server.web: INFO
 
---
spring.profiles: logging-debug
logging:
  file: logs/application.log
  level:
    org.thymeleaf: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.quartz.core: DEBUG
    org.h2.server.web: DEBUG
 
---
spring.profiles: logging-daily
logging:
  config: classpath:logback-spring.xml



