




spring:

  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      #url: jdbc:h2:mem:monitordb
      #url: jdbc:h2:tcp://localhost:8087/mem:infodb
      #url: jdbc:h2:mem:infodb;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=8087
      #url: jdbc:h2:tcp://127.0.0.1:9092/~/.h2/infodb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  
  devtools:
    livereload.enabled: true


logging:

  file:
    path: logs/
    max-size: 1MB
  
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"
    file: "%d %-5level [%-10thread] %-30logger{30} - %msg%n"
  
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace


job:
  default-path: lightnet/



########################################################
json:
  table-file:
    meta: src/main/resources/table/table_meta.json
    group: src/main/resources/table/table_group.json
    field-info: src/main/resources/table/table_field_info.json

    lightnet: src/main/resources/table/lightnet.json



########################################################
########################################################
spring.profiles.active: local-http

---
spring:
  profiles: local-http
  
server:
  port: 8088
  servlet.context-path: /v0.1

---
spring:
  profiles: local-https
  
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:serverkeystore.p12
    key-store-type: PKCS12
    key-store-password: server
    key-alias: serverkey
    



